services:
  - type: web
    name: fraud-detection-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SHOPIFY_API_KEY
        value: cd014c001d7a15705c088a24a2d97e9a
      - key: SHOPIFY_PASSWORD
        value: Hassan@512
      - key: SHOPIFY_STORE
        value: br0d07-7a.myshopify.com
